# Generated by Django 4.1.12 on 2024-02-26 18:40

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_centralcontroller_activate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='random_id',
            field=models.CharField(default=home.models.generar_id_aleatorio, max_length=16, verbose_name='Id aleatorio'),
        ),
        migrations.AddField(
            model_name='controller',
            name='random_id',
            field=models.CharField(default=home.models.generar_id_aleatorio, max_length=16, verbose_name='Id aleatorio'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='random_id',
            field=models.CharField(default=home.models.generar_id_aleatorio, max_length=16, verbose_name='Id aleatorio'),
        ),
    ]
